name: slack-notifications-pipeline

on:
  pull_request:
    branches: [ main ]
  
  push:
    branches: [ main ]

  workflow_dispatch:


jobs:
  Set-up-env:
    runs-on: windows-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: create venv and install pytest
        run: |
          python -m venv venv
          venv/Scripts/activate
          python -m pip install pytest

      - name: run tests
        run: |
          python -m pytest -v -s test

      


