name: slack-notifications-pipeline

on:
  pull_request:
    branches: [ main ]
  
  push:
    branches: [ main ]

  workflow_dispatch:


jobs:
  Python-tests:
    runs-on: windows-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: create venv and install pytest
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          venv/Scripts/activate

      - name: run tests
        run: |
          pip install pytest
          pytest --version
          pytest test

      - name: Notify slack of build status
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.BOT_USER_OAUTH_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: test-gh-actions-slack-notifications
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.BOT_USER_OAUTH_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: test-gh-actions-slack-notifications
          status: FAILED
          color: danger
        

  Slack-Notification:
    needs: Python-tests
    runs-on: ubuntu-latest # only runs on linux

    steps:
      - name: slack notification1
        if: github.event_name == 'pull_request'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: New ION PR opened!
          SLACK_MESSAGE: '${{ env.WORKFLOW_CONCLUSION }} :rocket:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: slack notification1
        if: github.event_name == 'push'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Recent Push to ION main!
          SLACK_MESSAGE: ':rocket:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: slack notification2
        uses: kpritam/slack-job-status-action@v1
        with: 
          job-status: ${{job.status}}
          slack-bot-token: ${{ secrets.APP_TOKEN }}

          
