name: slack-notifications-pipeline

on:
  pull_request:
    branches: [ main ]  
  
  push:
    branches: [ main ]

  workflow_dispatch:


jobs:
  Python-tests:
    runs-on: windows-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: create venv and install pytest
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          venv/Scripts/activate

      - name: run tests
        run: |
          pip install pytest
          pytest --version
          pytest test
        
  Python-tests2:
    runs-on: windows-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: create venv and install pytest
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          venv/Scripts/activate

      - name: run test
        run: |
          pip install pytest
          pytest --version
          pytest tests_2

      
  
  Slack-Notification:
    needs: [Python-tests, Python-tests2]
    runs-on: ubuntu-latest # only runs on linux
    if: always()

    steps:
      - name: slack notification1
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: New ION PR opened!
          SLACK_MESSAGE: ':rocket:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: slack notification fail 
        #if: github.event_name == 'push' && "${{ join(needs.*.result, ',') }}" == "failure"
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: "Build failed in main :rotating_light:"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "failure"
          SLACK_LINK_NAMES: true
          SLACK_MESSAGE: "@justin.ezell"

      # - name: slack notification success
      #   #if: github.event_name == 'push' && "${{ join(needs.*.result, ',') }}" == "success"
      #   if: ${{ contains(needs.*.result, 'success') }}
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_TITLE: "Build succeeded in main :tada:"
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_COLOR: "success"

      


